source/emp/emp_evaluation_system/urls.py
"""
For the evaluation system it is sufficient to provide all pages with a single view.
The only necessary parameter is thereby the page_slug (e.g. the "dashboard"
in http://localhost:8000/evaluation_system/dashboard/) which is used to retrieve the page
specific content from the DB.
"""
from django.urls import path

from .views import EvaluationSystemPageView

# Since the pages are build generic there is only one page template.
# This template builds a generic page out of admin specified data and multiple other templates.
urlpatterns = [
    path(
        "<slug:page_slug>/",
        EvaluationSystemPageView.as_view(
            template_name="./emp_evaluation_system/evaluationSystemPage.html"
        ),
    ),
]

source/emp/emp_main/urls.py
from importlib import import_module

from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from django.views.generic import RedirectView

from .views import EMPBaseView
from .api import api

ROOT_PATH = settings.ROOT_PATH

# This is the root for all API endpoints. This information is used
# here and there, especially in consumers.py and tests.
API_ROOT_PATH = "api/"


urlpatterns = [
    path("admin/", admin.site.urls),
    path(
        "", RedirectView.as_view(url=settings.HOME_PAGE_URL, permanent=False),
    ),
    path(
        "welcome/",
        EMPBaseView.as_view(template_name="./emp_main/welcome.html"),
        name="emp_main.welcome",
    ),
    # These are the URLS for REST API.
    # path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    path(API_ROOT_PATH, api.urls),
]

# Add url paths for the emp apps.
for emp_app in settings.EMP_APPS:
    # Compute the path for the urls of the module, but only if the
    # app_url_prefix has been defined.
    app_config = import_module(emp_app + ".apps")
    if not hasattr(app_config, "app_url_prefix"):
        continue
    if not app_config.app_url_prefix:
        continue
    # Add a trailing slash if it isn't existing yet.
    app_url_prefix = app_config.app_url_prefix
    if app_url_prefix[-1] != "/":
        app_url_prefix += "/"
    # Add urls of the app to urlpatterns.
    app_path = path(app_url_prefix, include(emp_app + ".urls"))
    urlpatterns.append(app_path)

urlpatterns = [path(ROOT_PATH, include(urlpatterns))] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

handler403 = "emp_main.views.emp_403_handler"

source/emp/emp_evaluation_system/models.py
import os

from django.db import models
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.utils import timezone

from multiselectfield import MultiSelectField


from emp_main import settings
from emp_main.models import Datapoint

from .apps import app_url_prefix

import re, datetime

class EvaluationSystemPage(models.Model):

    """
    Basic model for evaluation systems web pages. This pages will be configured in djangos admin panel.
    Use this model to create overview, dashboard, or comparison pages.
    """

    page_name = models.CharField(
        max_length = 18,
        help_text = (
            "The name of the page as displayed in the nav bar. Should not "
            "exceed 18 chars, as the string will be wider then the available "
            "space in the navbar."
        )
    )
    
    page_slug = models.SlugField(
        unique=True,
        help_text = (
            "The name of the page used in the URL of it. Must be unique "
            "as two pages of this app cannot have the same url."
        )
    ) 

    page_is_comparison_page = models.BooleanField(
        default = False,
        help_text = (
            "If this is checked, the page will transform into a optimization comparison page. "
            "Therefore the page consists of two algorithm select boxes and an additional comparison graph. "
            "Also the configured page will be rendered twice. Once for the first, once for the second selected algorithm."
        )
    )

    has_scroll_to_top_button = models.BooleanField(
        default = True,
         help_text = (
            "If checked the 'scroll top' button in the bottom right corner of the page will be visible "
            "providing the possibility scroll to the top of the page with one click."
        )
    )

    description = models.TextField(
        blank = True,
        default = "",
        help_text = (
            "Provide a description for this page to help other admin users to understand its purpose."
        )
    )

    def get_absolute_url(self):
        url = "/" + app_url_prefix + "/" + self.page_slug + "/"
        return url

    def __str__(self):
        if self.page_name is not None:
            return (str(self.id) + " - " + self.page_name)
        else:
            return str(self.id)

class PageElement(models.Model):
    """
    This model can used be in two states: container or presentation.
    If a UIElementContainer is used as container it consists of other UIElements (with arbitrary recursion).
    As UIElement it is used to visualize data.
    """

    ELEMENT_TYPE_CHOISES = [
        ("none","Choose elements type"),
        ("container","Container"),
        ("element", "Element")
    ]

    element_type = models.CharField(
        max_length = 9,
        choices = ELEMENT_TYPE_CHOISES,
        default = ELEMENT_TYPE_CHOISES[0][0],
        help_text = (
            "Choose the element type."
        )
    )

    page = models.ForeignKey(
        EvaluationSystemPage,
        default = None,
        on_delete = models.CASCADE
    )

class UIElementContainer(models.Model):

    """
    Container used to structure the UI.
    Consists of one to many UIElements that are rendered inside a bootstrap card as container.
    Use different containers to present different data.
    Containers may have a dropdown to provide extra functionality.
    """

    container_has_title = models.BooleanField(
        default = False,
        help_text = (
            "If checked the containers title will be visible in its header. "
            "Use short and describing titles to guide the user. "
        )
    )

    container_title = models.CharField(
        max_length = 64,
        help_text = (
            "The containers title as displaied in the containers header. "
            "Only visible if 'has_title' is checked. "
        )
    )

    container_has_dropdown = models.BooleanField(
        default = False,
        help_text = ( 
            "If checked the referenced dropdown linkes will be shown as a dropdown menu in the top right corner of the containers header. "
            "Use the dropdown menu to provide less important functionality in relation to containers data."
        )
    )

    container_dropdown_links = models.ManyToManyField(
        EvaluationSystemPage,
        blank = True,
        help_text = (
            "Choose the pages linked in the dropdown here."
        )
    )

    page_element = models.ForeignKey(
        PageElement,
        default = None,
        on_delete = models.CASCADE,
    )
    

class UIElement(models.Model):

    """
    UIElement model represents a ui element on a page. 
    It consists of data that will be visualized with the help of a presentation object.
    UIElements can be grouped in UIElementContainers or added alone to a page.
    """
    page_element = models.ForeignKey(
        PageElement,
        default = None,
        on_delete = models.CASCADE,
        blank=True,
        null=True
    )

    container_element = models.ForeignKey(
        UIElementContainer,
        default = None,
        on_delete = models.CASCADE,
        blank=True,
        null=True
    )

class Metric(models.Model):

    """
        A Metric object represents a formula on one to may Datapoints.
        The formula may be specified as a String. 
        Later on the String will be parsed, the linked datapoint values requested, and a Metric result calculated.
        At the frontend only results will be presented.
    """
    
    name = models.CharField(
        max_length = 128,
        blank = False,
        default = None,
        null = True,
        help_text = (
            "The metric's name. It will appear as data description in the frontend."
        )
    )

    unit = models.CharField(
        max_length = 64,
        blank = False,
        default = "$",
        help_text = (
            "The unit of the metrics result."
        )
    )

    formula = models.CharField(
        max_length = 256,
        blank = False,
        null = True,
        default = None,
        help_text = (
            "Describe the metrics formula as the following: use basic mathematic specail characters like '+', '-', '*', '/', '(' and ')'. "
            "Aslo you may use numbers in integer or floating point format. " 
            "As variable you can link a datapoint using dp_* with * as data point id."
            "The last value of this datapoint will be used as value."
            "Do NOT use whitespaces!"
        )
    )

    description = models.TextField(
        default = None,
        null = True,
        help_text = (
            "Provide a description for other users. This description will only be shwon in admin panel context."
        )
    )
    
    def __str__(self):
        if self.name is not None:
            return (str(self.id) + " - " + self.name)
        else:
            return str(self.id)

class Presentation(models.Model):

    """
    The Presentation model is used to link a presentation type (card, chart...) to a UIElement.
    UIElements data will be visualized with Presentations help.
    """
    
    PRESENTATION_TYPE_CHOISES = [
        ("card","card"),
        ("chart", "chart")
    ]

    presentation_type = models.CharField(
        max_length = 5,
        choices = PRESENTATION_TYPE_CHOISES,
        default = PRESENTATION_TYPE_CHOISES[0][0],
        help_text = (
            "Choose the presentation type."
        )
    )

    ui_element = models.ForeignKey(
        UIElement,
        default = None,
        on_delete = models.CASCADE,
    )

    use_metric = models.BooleanField(
        default = False,
        blank = False,
        help_text = (
            "Check this if you want to use a Metric object instead of a Datapoint object."
        )
    )

    datapoint = models.ForeignKey(
        Datapoint,
        on_delete = models.SET_NULL,
        default = None,
        blank = True,
        null = True,
        help_text = (
            "Choose the Datapoint represented by this."
        )
    )

    metric = models.ForeignKey(
        Metric,
        on_delete = models.SET_NULL,
        default = None,
        blank = True,
        null = True,
        help_text = (
            "Choose the Metric represented by this."
        )
    )

    

class Card(models.Model):
    """
    The Card model is one of Presentation models types.
    Its a rectangular bootstrap card, containing an image, a data title, presented in monochrome design.
    As additional decoration elements a border on the left or at the bottom are available.
    To add extra information use the tooltips. 
    For additional fuctionality use the card as button.

    Use this presentation type to visualize simple data. 
    """
    CARD_COLOR_CHOICES = [
        ("primary", "primary"),
        ("secondary", "secondary"),
        ("success", "success"),
        ("warning", "warning"),
        ("danger", "danger"),       
    ]

    card_color = models.CharField(
        max_length= 10,
        choices = CARD_COLOR_CHOICES,
        default = CARD_COLOR_CHOICES[0][0],
        help_text = (
            "Allows configuring the color scheme of the card. "
        )
    )

    CARD_DECORATION_CHOICES = [
        ("none", "none"),
        ("left", "left"),
        ("bottom", "bottom"),     
    ]

    card_decoration = models.CharField(
        max_length = 6,
        choices = CARD_DECORATION_CHOICES,
        default = CARD_DECORATION_CHOICES[0][0],
        help_text = (
            "Allows configuring the decoration of the card. "
        )
    )

    card_is_button = models.BooleanField(
        default = False,
        help_text = (
            "If checkt the card can be used as button using the referenced link. "
            "With hover effects the card is made recognizable as button. "

source/emp/emp_evaluation_system/views.py
from django.shortcuts import get_object_or_404

from emp_main.views import EMPBaseView
from emp_main.settings import EMP_EVALUATION_PAGE_UPDATE_INTERVAL
from .models import EvaluationSystemPage, Algorithm
class EvaluationSystemPageView(EMPBaseView):
    """
    View for EvaluationSystemPages.
    Setting up the context.
    """

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        page_slug = self.kwargs["page_slug"]
        page_object = get_object_or_404(EvaluationSystemPage, page_slug=page_slug)

        # Put important page date into context here
        context["page_name"] = page_object.page_name
        context["is_comparison_page"] = page_object.page_is_comparison_page
        context["pagelements"] = page_object.pageelement_set.all
        context["has_scroll_to_top_button"] = page_object.has_scroll_to_top_button      
        context["update_interval"] = EMP_EVALUATION_PAGE_UPDATE_INTERVAL

        # If the page object is used as a comparison page, all Algorithm objects will be put into context.
        # They can be choosen in comparison pages dropdowns at the top of the paqge.
        if page_object.page_is_comparison_page:
            context["algorithms"] = Algorithm.objects.all()
            context["comparison_graphs"] = page_object.comparisongraph_set.all

        return context

source/emp/emp_evaluation_system/templates/emp_evaluation_system/algorithm_selection_form.html
{% comment %}
    This template represents the settings section for a comparison page.
    The settings section consists of two selection forms for selection of the simulation and optimization algorithms to compare.
    Also there are two date pickers to select the start and end date of the simulation.
    Beneath them there is a button that starts the simulation.
{% endcomment %}
<div class="row">
    <div class="col-md-6 mb-4 px-4">
        <select class="form-control" id="leftAlgorithmSelection">
            {% for algorithm in algorithms%} 
                <option value="{{algorithm.backend_identifier}}" >{{algorithm.name}}</option>
            {% endfor %}
        </select>
        <div class="form-group">
            <label for="start_time">Simulation Start Time:</label>
            <input class="form-control" type="date" id="start_time" name="simulation_start_time"
                value='{% now "Y-m-d" %}'
                    min="2000-1-1" max='2100-1-1'>
        </div>
    </div>
    <div class="col-md-6 mb-4 px-4">
            <select class="form-control" id="rightAlgorithmSelection">
                {% for algorithm in algorithms%} 
                    <option value="{{algorithm.backend_identifier}}" >{{algorithm.name}}</option>
                {% endfor %}
            </select>
            <div class="form-group">
                <label for="end_time">Simulation End Time:</label>
                <input class="form-control" type="date" id="end_time" name="simulation_end_time"
                    value='{% now "Y-m-d" %}'
                    min="2000-1-1" max='2100-1-1'>
            </div>
    </div>
</div>
<div class="row justify-content-md-center">
    <button type="button" class="btn btn-danger" id="btn_settings" onclick="startSimulation()">Start Simulation</button>
</div>
<hr>

source/emp/emp_evaluation_system/templates/emp_evaluation_system/card.html
{% comment %}
    This is the html template for a card model.
    As base construct a bootstrap card is used. 
    Cusomizable elements: 
        - Card decoration (left, bottom, none)
        - Card icon (Choose out of a selection of fontawesome icons)
        - Card color (Font, icon, decoration)
        - Card tooltip
        - Card as button -> Link to another EvaluationSystemPage
    The in the parent Presentation element linked Datapoint values will be shown as card text.
{% endcomment %} 
{% load datapoint_helpers %}
<div class="{% if is_comparison_page %}col-sm-12{% else %}col-xl-3 col-md-6{% endif %} mb-4">
    <div class="card {% if card.card_decoration != 'none' %} border-{{card.card_decoration}}-{{card.card_color}} {% endif %} 
    shadow h-100 py-2" hoverable="{{card.card_is_button}}"
    {% if card.card_is_button%} onclick="window.location='{{card.card_button_link.get_absolute_url}}'" {% endif %} 
    {% if card.card_has_tooltip %}title="{{card.card_tooltip_text}}"{% endif %} >
        <div class="card-body">
            <div class="row no-gutters align-items-center">
                <div class="col mr-2">
                    {% if not is_comparison_page %}
                        {% if presentation.use_metric %}
                            <div class="text-xs font-weight-bold text-{{card.card_color}} text-uppercase mb-1">
                                {{presentation.metric.name}}</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800"><span class="mt_{{presentation.metric.id}}_realtime_metric" formula={{presentation.metric.formula}}>N/A</span> {{presentation.metric.unit}} </div>
                        {% else %}
                            <div class="text-xs font-weight-bold text-{{card.card_color}} text-uppercase mb-1">
                                {{datapoint.short_name}}</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">{% dp_field_value presentation.datapoint "last_value" field_collector %} {% dp_field_value presentation.datapoint "unit" field_collector %} </div>
                        {% endif %}
                    {% else %}
                        {% if presentation.use_metric %}
                            <div class="text-xs font-weight-bold text-{{card.card_color}} text-uppercase mb-1">
                                {{presentation.metric.name}}</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800"><span class="mt_{{presentation.metric.id}}_simulated_metric_{{side}}" formula={{presentation.metric.formula}}>N/A</span> {{presentation.metric.unit}} </div>
                        {% else %}
                            <div class="text-xs font-weight-bold text-{{card.card_color}} text-uppercase mb-1">
                                {{datapoint.short_name}}</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800"><span class="dp_{{presentation.datapoint.origin_id}}_simulated_value_{{side}}">N/A</span> {% dp_field_value presentation.datapoint "unit" field_collector %} </div>
                        {% endif %}
                    {% endif %}
                </div>
                <div class="col-auto">
                    <i class="fas fa-{{card.card_icon}} fa-2x icon-{{card.card_color}}"></i>
                </div>
            </div>
        </div>
    </div>
</div>

source/emp/emp_evaluation_system/templates/emp_evaluation_system/chart.html
{% comment %}
    This is the html template for a Chart model object.
    As base consturct a bootstrap card with header is used to contain the canvas where the chart is printed.
    The chart is printed by the vendor/chart.js/Chart.js library and our own code in  js/charts.js.
    Costomizable elements are:
        - Chart title in the card header.
        - The dropdown menu's links. These will change the chart's data set intervals.
        - Chart type (area, bar, doughnut)
        - Chart data sets.
    The in the parent Presentation element linked Datapoint values will be shown as chart datasets. 
{% endcomment %}
<div class="col-xl-12 col-lg-12">
    <div class="card shadow mb-4">
        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
            {% comment%} 
                Charts header is included here
            {% endcomment %}
            {% if chart.chart_has_title %}
                <h6 class="m-0 font-weight-bold text-primary">{{chart.chart_title}}</h6>
            {% endif %}
            <div class="dropdown no-arrow">
                <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
                    aria-labelledby="dropdownMenuLink">
                    <div class="dropdown-header">Change Interval</div>
                    {% comment %} 
                        For every data interval chosen, when configuring the chart in the admin panel,
                        a links is included.
                    {% endcomment %}
                    {% for label in chart.chart_data_interval %}
                        <a class="dropdown-item" onclick='changeDataIntervalTo(this, "{{label}}")'> {{label}} </a>
                    {% endfor %} 
                </div>
            </div>
        </div>
        <!-- Card Body -->
        <div class="card-body">
            <div class="chart-area">
                {% comment %}
                    A canvas with all important data is created.
                    This data needs to be set as HTML element attributes, therefore data can be read from other files as well.
                    The chart will be build on the document ready event.
                {% endcomment %}
                {% if not presentation.use_metric and  not is_comparison_page %}
                    {% comment %}
                        Chart with realtime values.
                    {% endcomment %}
                    <canvas class="dp_{{presentation.datapoint.id}}_{{chart.chart_type}}_chart_realtime_value" datapointId="{{datapoint.id}}" dataTypes="{{chart.chart_data_sets}}" 
                    dataIntervals="{{chart.chart_data_interval}}"></canvas>
                {% elif presentation.use_metric and  not is_comparison_page %}
                    {% comment %}
                        Chart with realtime metrics.
                        TODO Implement Charts mit normalen Metriken
                        <canvas class="mt_{{presentation.metric.id}}_{{chart-chart.chart_type}}_chart_realtime_metric" datapointId="{{datapoint.id}}" dataTypes="{{chart.chart_data_sets}}" 
                    dataIntervals="{{chart.chart_data_interval}}"></canvas>
                    {% endcomment %}
                {% elif not presentation.use_metric and is_comparison_page%}
                    {% comment %}
                        Chart with simulated values.
                    {% endcomment %}
                        <canvas class="dp_{{presentation.datapoint.origin_id}}_{{chart.chart_type}}_chart_simulated_value_{{side}}" dataTypes="{{chart.chart_data_sets}}" 
                    dataIntervals="{{chart.chart_data_interval}}" datapointId="{{datapoint.id}}"></canvas>
                {% else %}
                    {% comment %}
                        Chart with metrics over simulated values.
                    {% endcomment %}
                    <canvas class="mt_{{presentation.metric.id}}_{{chart.chart_type}}_chart_simulated_metric_{{side}}" dataTypes="{{chart.chart_data_sets}}" 
                    dataIntervals="{{chart.chart_data_interval}}"  formula="{{presentation.metric.formula}}"></canvas>
                {% endif %}
                
            </div>
        </div>
    </div>
</div>

source/emp/emp_evaluation_system/templates/emp_evaluation_system/comparison_graph.html
{% comment %}
    Loading evulation page tags.
    These are reuqired for data processing when setting up comparioson graphs.
{% endcomment %}
{% load evaluationpage_tags %}

{% comment %}
    Setting up a comparion graph.
    Each graph consists of a dynamic title and a canvas where the graph will be print.
    The canvas holds all important data for the graph setup handled by the static/emp_evaluation_system/js/charts.js and the static/emp_evaluation_system/js/simulation.js file.
{% endcomment %}
<div class="col-12">
    <div class="card shadow mb-4">
        <div class="card-header py-3">
        {% if graph.has_title %}
            <h6 class="m-0 font-weight-bold text-primary">{{graph.chart_title}}</h6>
        {% endif %}
        </div>
        <div class="card-body">
            <div class="chart-area" >
                 <canvas class="cc_{{graph.id}}" 
                 using_metric="{% using_metrics graph.comparisongraphdataset_set.all %}"
                 data="{% get_datapoints_or_formulas graph.comparisongraphdataset_set.all %}"
                 type="{{graph.type}}"></canvas>
            </div>
        </div>
    </div>
</div>

source/emp/emp_evaluation_system/templates/emp_evaluation_system/pageelement.html
{% comment %}   
    This template only distinguishes between UIContainerElement and UIElement PageElements.
    The element types HTML template then will be included.
{% endcomment %}

{% if element.element_type == "container"%}
    {% with element.uielementcontainer_set.all|first as container %}
        {% include "emp_evaluation_system/uielementcontainer.html" %}
    {% endwith %}   
{% elif element.element_type == "element" %}
    {% with element.uielement_set.all|first as element %}
        {% include "emp_evaluation_system/uielement.html" %}
    {% endwith %}
{% endif%}

source/emp/emp_evaluation_system/templates/emp_evaluation_system/presentation.html
{% comment %}    
    This template only distinguishes between Chart and Card (possibly more comming) Presentations.
    The presentation types HTML template then will be included.
{% endcomment %}

{% if presentation.presentation_type == "chart"%}
    {% with chart=presentation.chart_set.all|first datapoint=presentation.datapoint  %}
        {% include "emp_evaluation_system/chart.html" %}
    {% endwith %}   
{% elif presentation.presentation_type == "card" %}
    {% with card=presentation.card_set.all|first  datapoint=presentation.datapoint %}
        {% include "emp_evaluation_system/card.html" %}
    {% endwith %}
{% endif%}

source/emp/emp_evaluation_system/templates/emp_evaluation_system/uielement.html
{% comment %}
    The only purpose of this template is to include the presentation template.
    This template might seem redundant but its used to represent the systems architecture.
{% endcomment %}
{% with element.presentation_set.all|first as presentation %}
    {% include "emp_evaluation_system/presentation.html" %}
{% endwith %}

source/emp/emp_evaluation_system/templates/emp_evaluation_system/uielementcontainer.html
{% comment %}
    This templated provides a basic bootstrap card (we call it 'container' in this project).
    Using the Container model fields to build a working container.
    A Container consits of one or many other PageElemets, they can be a UIElement or a UIElementContainer as well.

    Using the Container model fields following container attributes are configureable:
        - Container title
        - Container dropdown and its dropdown links to other EvaluationSystemPages.
        - The pagelements the container consists of.
{% endcomment %}

<div class="col">
    <div class="card shadow mb-4">
        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
            {% comment %} Including the containers title if the model has a title {% endcomment %}
            {% if container.container_has_title %}
                <h6 class="m-0 font-weight-bold text-primary">{{container.container_title}}</h6>
            {% endif %}
            {% comment %} Including a dropdown menu and its links if the model has a dropdown {% endcomment %}
            {% if container.container_has_dropdown %}
                <div class="dropdown no-arrow">
                    <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
                        aria-labelledby="dropdownMenuLink">
                        {% for link in container.container_dropdown_links.all %}
                            <a class="dropdown-item" href="{{link.get_absolute_url}}"> {{link.page_name}} </a>
                        {% endfor %}
                    </div>
                </div>
            {% endif %}
        </div>
        {% comment %}
            Here all elements included in the container are included.
        {% endcomment %}
        <div class="card-body">
            <div class="row">
                {% for element in container.uielement_set.all%}
                    {% include "emp_evaluation_system/uielement.html" %}
                {% endfor %}
            </div>
           
        </div>
    </div>
</div>